### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [artiebears13/Sirius-c-Projects#2]
Список лучше сделать классом, а не структурой.

**Comment by artiebears13** [comment]
Добрый вечер! Поменял struct на class

**Comment by dzheltkov** [comment]
Да, ещё я вчера это пропустил, не хватает деструктора у списка -- поэтому при уничножении объъекта класса происходит утечка памяти.

**Comment by artiebears13** [comment]
Добрый день! я добавил деструктор, однако почему то он вызывается 2 раза и во второй раз крашится, не могу понять почему.

**Comment by artiebears13** [comment]
Починил, теперь работает правильно

**Comment by dzheltkov** [comment]
Задание зачту, но вообще так как класс не шаблонный, то для функций реализованных в заголовочном файле нужно использовать спецификатор inline.
Кроме того, не нужно использовать одновременно и 
```
#ifndef LINKED_LIST_LIST_H
#define LINKED_LIST_LIST_H
```
и
```#pragma once```
Используйте что-то одно из этого.
